version: '3'

tasks:
  start:
    desc: 'Start the Docker services in detached mode'
    cmds:
      - sudo docker-compose up --build

  stop:
    desc: 'Stop the Docker services'
    cmds:
      - sudo docker compose down

  restart:
    desc: 'Restart the Docker services'
    cmds:
      - docker compose down
      - docker compose up -d

  logs:
    desc: 'View the logs of the Docker services'
    cmds:
      - docker compose logs

  clean:
    desc: 'Stop and remove Docker services and volumes'
    cmds:
      - sudo docker-compose down --rmi all
  serve:
    desc: 'Start the server'
    cmds:
      - yarn run start:dev
