# Postgres Container
FROM postgres:17

# Set environment variables
ENV POSTGRES_DB postgres
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD postgres

# Expose the default PostgreSQL port (5432)
EXPOSE 5432