export default {
  success: true,
  status: 'SUCCESS',
  code: 200,
  payload: [
    {
      accounts: [],
      type_id: 'zip_code_v1',
      type: 'demographic',
      display_name: 'Zip code',
      description:
        'Provide a Zip code and a maximum distance in km (format: "ZIP,DISTANCE")',
      value_type:
        '[{"type":"string","label":"ZIP","description":"A zip code"},{"type":"number","label":"distance","description":"Distance in kilometers"}]',
      allowed_operators: ['less than'],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'brand_last_order_date_v1',
      type: 'order',
      display_name: 'Last Date Ordered from Brand',
      description:
        'Date of most recent order from a given brand (enter brand name or ID)',
      value_type:
        '[{"type":"string","label":"brand","description":"Brand identifier"},{"type":"date","label":"date","description":"Latest order date (YYYY-MM-DD)"}]',
      allowed_operators: [
        'less than',
        'greater than',
        'less than or equal to',
        'greater than or equal to',
      ],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'brand_order_count_total_v1',
      type: 'order',
      display_name: 'Orders Overall from Brand',
      description:
        'Provide a brand identifier and a number of orders (format: "BRAND,COUNT")',
      value_type:
        '[{"type":"string","label":"brand","description":"Brand identifier"},{"type":"number","label":"count","description":"Number of orders"}]',
      allowed_operators: [
        'less than',
        'greater than',
        'less than or equal to',
        'greater than or equal to',
      ],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'brand_order_count_last_x_days_v1',
      type: 'order',
      display_name: 'Orders from Brand in Last x Days',
      description:
        'Enter days; counts orders from the brand within that period (format: "BRAND,DAYS")',
      value_type:
        '[{"type":"string","label":"brand","description":"Brand identifier"},{"type":"number","label":"days","description":"Number of days"}]',
      allowed_operators: [
        'less than',
        'greater than',
        'less than or equal to',
        'greater than or equal to',
      ],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'category_last_order_date_v1',
      type: 'order',
      display_name: 'Last Date Ordered from Category',
      description:
        'Date of most recent order from a given category (enter category name or ID)',
      value_type:
        '[{"type":"string","label":"category","description":"Category identifier"},{"type":"date","label":"date","description":"Latest order date (YYYY-MM-DD)"}]',
      allowed_operators: [
        'less than',
        'greater than',
        'less than or equal to',
        'greater than or equal to',
      ],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'category_order_count_total_v1',
      type: 'order',
      display_name: 'Orders Overall from Category',
      description:
        'Provide a category identifier and a number of orders (format: "CATEGORY,COUNT")',
      value_type:
        '[{"type":"string","label":"category","description":"Category identifier"},{"type":"number","label":"count","description":"Number of orders"}]',
      allowed_operators: [
        'less than',
        'greater than',
        'less than or equal to',
        'greater than or equal to',
      ],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'category_order_count_last_x_days_v1',
      type: 'order',
      display_name: 'Orders from Category in Last x Days',
      description:
        'Enter days; counts orders from the category within that period (format: "CATEGORY,DAYS")',
      value_type:
        '[{"type":"string","label":"category","description":"Category identifier"},{"type":"number","label":"days","description":"Number of days"}]',
      allowed_operators: [
        'less than',
        'greater than',
        'less than or equal to',
        'greater than or equal to',
      ],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'singlebrand_buyer_v1',
      type: 'order',
      display_name: 'Single-brand Buyer',
      description: 'Has the customer only ever purchased from a single brand?',
      value_type: 'boolean',
      allowed_operators: ['is true', 'is false'],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'click_collect_v1',
      type: 'order',
      display_name: 'Click & Collect Buyer',
      description:
        'Has placed \u22651 order with delivery option "Click & Collect"?',
      value_type: 'boolean',
      allowed_operators: ['is true', 'is false'],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'last_login_date_v1',
      type: 'account',
      display_name: 'Last Login Date',
      description: 'Date of last login to the website (YYYY-MM-DD)',
      value_type: 'date',
      allowed_operators: [
        'less than',
        'greater than',
        'less than or equal to',
        'greater than or equal to',
      ],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'last_order_date_v1',
      type: 'order',
      display_name: 'Last Order Date',
      description:
        'Select customers by the date of their most recent order (YYYY-MM-DD)',
      value_type: 'date',
      allowed_operators: [
        'less than',
        'greater than',
        'less than or equal to',
        'greater than or equal to',
      ],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'first_order_date_v1',
      type: 'order',
      display_name: 'First Order Date',
      description:
        'Select customers by the date of their first order (YYYY-MM-DD)',
      value_type: 'date',
      allowed_operators: [
        'less than',
        'greater than',
        'less than or equal to',
        'greater than or equal to',
      ],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'cart_last_activity_date_v1',
      type: 'preferences',
      display_name: 'Last Cart Activity Date',
      description: 'Date of last addition to cart (YYYY-MM-DD)',
      value_type: 'date',
      allowed_operators: [
        'less than',
        'greater than',
        'less than or equal to',
        'greater than or equal to',
      ],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'age_v1',
      type: 'demographic',
      display_name: 'Age',
      description: 'Filter by customer age in years',
      value_type: 'number',
      allowed_operators: [
        'less than',
        'greater than',
        'less than or equal to',
        'greater than or equal to',
      ],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'order_revenue_last_x_days_v1',
      type: 'order',
      display_name: 'Order Revenue in Last x Days',
      description: 'Enter days to sum revenue within that period',
      value_type: 'number',
      allowed_operators: [
        'less than',
        'greater than',
        'less than or equal to',
        'greater than or equal to',
      ],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'lifetime_order_value_v1',
      type: 'order',
      display_name: 'Lifetime Order Value',
      description: 'Filter by total value of all orders per customer to date',
      value_type: 'number',
      allowed_operators: [
        'less than',
        'greater than',
        'less than or equal to',
        'greater than or equal to',
      ],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'promo_code_usage_v1',
      type: 'order',
      display_name: 'Promotion Code Usage Count',
      description: 'Total number of times customer has used any promotion code',
      value_type: 'number',
      allowed_operators: [
        'less than',
        'greater than',
        'less than or equal to',
        'greater than or equal to',
      ],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'order_margin_total_v1',
      type: 'order',
      display_name: 'Total Order Margin',
      description: 'Total gross margin across all customer orders',
      value_type: 'number',
      allowed_operators: [
        'less than',
        'greater than',
        'less than or equal to',
        'greater than or equal to',
      ],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'order_revenue_total_v1',
      type: 'order',
      display_name: 'Total Order Revenue',
      description: 'Total revenue across all customer orders',
      value_type: 'number',
      allowed_operators: [
        'less than',
        'greater than',
        'less than or equal to',
        'greater than or equal to',
      ],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'avg_order_value_v1',
      type: 'order',
      display_name: 'Average Order Value',
      description: 'Filter by average value of all orders per customer',
      value_type: 'number',
      allowed_operators: [
        'less than',
        'greater than',
        'less than or equal to',
        'greater than or equal to',
      ],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'points_usage_v1',
      type: 'order',
      display_name: 'Points Usage Count',
      description: 'Total number of points the customer has redeemed',
      value_type: 'number',
      allowed_operators: [
        'less than',
        'greater than',
        'less than or equal to',
        'greater than or equal to',
      ],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'order_margin_last_x_days_v1',
      type: 'order',
      display_name: 'Order Margin in Last x Days',
      description: 'Enter days to sum margin within that period',
      value_type: 'number',
      allowed_operators: [
        'less than',
        'greater than',
        'less than or equal to',
        'greater than or equal to',
      ],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'time_between_orders_v1',
      type: 'order',
      display_name: 'Time Between Orders (days)',
      description: 'Average time in days between customer orders',
      value_type: 'number',
      allowed_operators: [
        'less than',
        'greater than',
        'less than or equal to',
        'greater than or equal to',
      ],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'order_count_last_x_days_v1',
      type: 'order',
      display_name: 'Number of Orders in the Last x Days',
      description:
        'Enter the number of days to count orders within that period',
      value_type: 'number',
      allowed_operators: [
        'less than',
        'greater than',
        'less than or equal to',
        'greater than or equal to',
      ],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'order_count_total_v1',
      type: 'order',
      display_name: 'Number of Orders Overall',
      description: 'Total number of orders placed by the customer',
      value_type: 'number',
      allowed_operators: [
        'less than',
        'greater than',
        'less than or equal to',
        'greater than or equal to',
      ],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'points_expiring_soon_v1',
      type: 'points',
      display_name: 'Points Expiring Soon',
      description:
        'Number of points set to expire within the next X days (enter days)',
      value_type: 'number',
      allowed_operators: [
        'less than',
        'greater than',
        'less than or equal to',
        'greater than or equal to',
      ],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'lifetime_points_earned_v1',
      type: 'points',
      display_name: 'Lifetime Points Earned',
      description: 'Total points earned to date',
      value_type: 'number',
      allowed_operators: [
        'less than',
        'greater than',
        'less than or equal to',
        'greater than or equal to',
      ],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'current_points_balance_v1',
      type: 'points',
      display_name: 'Current Points Balance',
      description: 'Customer\u2019s current reward points balance',
      value_type: 'number',
      allowed_operators: [
        'less than',
        'greater than',
        'less than or equal to',
        'greater than or equal to',
      ],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'lifetime_points_redeemed_v1',
      type: 'points',
      display_name: 'Lifetime Points Redeemed',
      description: 'Total points redeemed to date',
      value_type: 'number',
      allowed_operators: [
        'less than',
        'greater than',
        'less than or equal to',
        'greater than or equal to',
      ],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'redemption_rate_v1',
      type: 'points',
      display_name: 'Redemption Rate',
      description: 'Ratio of points redeemed to points earned (as percentage)',
      value_type: 'number',
      allowed_operators: [
        'less than',
        'greater than',
        'less than or equal to',
        'greater than or equal to',
      ],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'cart_total_value_v1',
      type: 'preferences',
      display_name: 'Cart Total Value',
      description: 'Total monetary value of items in cart',
      value_type: 'number',
      allowed_operators: [
        'less than',
        'greater than',
        'less than or equal to',
        'greater than or equal to',
      ],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'cart_item_count_v1',
      type: 'preferences',
      display_name: 'Cart Item Count',
      description: 'Number of items currently in cart',
      value_type: 'number',
      allowed_operators: [
        'less than',
        'greater than',
        'less than or equal to',
        'greater than or equal to',
      ],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'account_type_v1',
      type: 'account',
      display_name: 'Account Type',
      description: 'Guest or Registered Account',
      value_type: 'string',
      allowed_operators: ['matches exactly'],
      possible_values: ['Guest', 'Registered'],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'membership_club_v1',
      type: 'account',
      display_name: 'Membership Club',
      description:
        'Customer membership group or tier (e.g. Silver, Gold, Platinum)',
      value_type: 'string',
      allowed_operators: ['matches exactly', 'contains'],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'region_v1',
      type: 'demographic',
      display_name: 'Region',
      description: 'Provide a region name or code (e.g. state, province)',
      value_type: 'string',
      allowed_operators: ['matches exactly', 'contains'],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'gender_v1',
      type: 'demographic',
      display_name: 'Gender',
      description: 'Select customer gender',
      value_type: 'string',
      allowed_operators: ['matches exactly'],
      possible_values: ['Male', 'Female', 'Other'],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'most_purchased_category_v1',
      type: 'order',
      display_name: 'Most Purchased Category',
      description:
        'Filter customers whose most frequently purchased category is the specified category',
      value_type: 'string',
      allowed_operators: ['matches exactly', 'does not match exactly'],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'promo_code_redeemed_v1',
      type: 'order',
      display_name: 'Has Redeemed Promotion Code',
      description:
        'Enter a promotion code to filter customers who have redeemed it',
      value_type: 'string',
      allowed_operators: ['matches exactly'],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'most_purchased_subcategory_v1',
      type: 'order',
      display_name: 'Most Purchased Subcategory',
      description:
        'Filter customers whose most frequently purchased subcategory is the specified subcategory',
      value_type: 'string',
      allowed_operators: ['matches exactly', 'does not match exactly'],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'order_channel_v1',
      type: 'order',
      display_name: 'Order Channel',
      description:
        'Select one or more order channels (e.g. SEA, SEO, NL, Telefon, Bestelltalon)',
      value_type: 'string',
      allowed_operators: ['contains', 'does not contain'],
      possible_values: ['SEA', 'SEO', 'NL', 'Telefon', 'Bestelltalon'],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'most_purchased_brand_v1',
      type: 'order',
      display_name: 'Most Purchased Brand',
      description:
        'Filter customers whose most frequently purchased brand is the specified brand',
      value_type: 'string',
      allowed_operators: ['matches exactly', 'does not match exactly'],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'advertising_medium_v1',
      type: 'order',
      display_name: 'Advertising Medium',
      description:
        'Enter one or more medium codes (e.g. LV01, BW02, WG03, VE04) \u2013 matches orders by that channel',
      value_type: 'string',
      allowed_operators: ['contains', 'does not contain'],
      possible_values: ['LV01', 'BW02', 'WG03', 'VE04'],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'cart_content_category_v1',
      type: 'preferences',
      display_name: 'Cart: Category',
      description:
        'Filter by categories currently in the cart (comma-separated)',
      value_type: 'string',
      allowed_operators: ['contains', 'does not contain'],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'cart_content_brand_v1',
      type: 'preferences',
      display_name: 'Cart: Brand',
      description: 'Filter by brands currently in the cart (comma-separated)',
      value_type: 'string',
      allowed_operators: ['contains', 'does not contain'],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'sperren_v1',
      type: 'preferences',
      display_name: 'Communication Blocks',
      description:
        'Select one or more block types: Post, Delivery, Advertising, Communication (comma-separated)',
      value_type: 'string',
      allowed_operators: ['contains', 'does not contain'],
      possible_values: ['Post', 'Delivery', 'Advertising', 'Communication'],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'catalog_mailer_recipient_v1',
      type: 'preferences',
      display_name: 'Catalog\/Mailer Recipient',
      description: 'Enter catalog or mailing identifier (alphanumeric code)',
      value_type: 'string',
      allowed_operators: ['matches exactly', 'does not match exactly'],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'cart_content_product_v1',
      type: 'preferences',
      display_name: 'Cart: Product',
      description:
        'Filter by specific products in the cart (comma-separated IDs or names)',
      value_type: 'string',
      allowed_operators: ['contains', 'does not contain'],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'viewed_category_v1',
      type: 'website_activity',
      display_name: 'Viewed Product Category',
      description:
        'Filter customers who viewed products from a specific category (enter category ID or name)',
      value_type: 'string',
      allowed_operators: ['contains'],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'viewed_brand_v1',
      type: 'website_activity',
      display_name: 'Viewed Product Brand',
      description:
        'Filter customers who viewed products from a specific brand (enter brand ID or name)',
      value_type: 'string',
      allowed_operators: ['contains'],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
    {
      accounts: [],
      type_id: 'viewed_url_v1',
      type: 'website_activity',
      display_name: 'Viewed URL',
      description:
        'Filter customers by URLs they have visited (partial match allowed)',
      value_type: 'string',
      allowed_operators: ['contains'],
      possible_values: [],
      is_required: false,
      created_at: '2025-05-22 14:08:18.683932+00:00',
      updated_at: '2025-05-22 14:08:18.683932+00:00',
      is_deleted: false,
    },
  ],
  tm: '20250723060624',
  errors: [],
};
