export const actionStack = {
  stack: [
    {
      lastMove: 'execute',
      name: 'Delete',
      resource: {
        widget_use_case: '44f7546d-ae28-31d6-eb1b-a0585220a104',
        use_case_id: 'click_revenue_statistics_v1',
        widget_ids: ['addtocart'],
        name: 'Click Revenue Statistics',
        category: 'sales',
        tooltip: [
          { language: 'en', value: 'Analyze click-to-revenue statistics.' },
        ],
        order: null,
        property_values: [
          {
            property_name: 'time_range',
            property_values: [''],
            default_values: [''],
            widget_property_values: [
              { widget_id: 'addtocart', property_values: [''] },
            ],
          },
          {
            property_name: 'statistic_type',
            property_values: [''],
            default_values: [''],
            widget_property_values: [
              { widget_id: 'addtocart', property_values: [''] },
            ],
          },
          {
            property_name: 'boostWeight',
            property_values: ['0.5'],
            default_values: ['0.5'],
            widget_property_values: [
              { widget_id: 'addtocart', property_values: ['0.5'] },
            ],
          },
        ],
        string_attributes: [],
        localized_string_attributes: [],
        numeric_attributes: [],
        localized_numeric_attributes: [],
        datetime_attributes: [],
        localized_datetime_attributes: [],
        creation_tm: null,
        last_update_tm: null,
        last_update_user: null,
        ab_test: null,
        active: true,
        segment: null,
        advanced_options: null,
      },
    },
    {
      lastMove: 'execute',
      name: 'Create',
      payload: {
        widget_use_case: '2ba2a320-b7ab-4f2b-bd4f-92a71e603b14',
        use_case_id: 'sold_times_v1',
        widget_ids: ['addtocart'],
        name: 'Sold Count',
        category: 'filtering rules',
        tooltip: [
          {
            language: 'en',
            value: 'Filter products by minimum number of times sold.',
          },
        ],
        order: null,
        property_values: [
          {
            property_name: 'min_times_sold',
            property_values: [''],
            default_values: [''],
            widget_property_values: [
              { widget_id: 'addtocart', property_values: [''] },
            ],
          },
          {
            property_name: 'filter_enabled',
            property_values: [''],
            default_values: [''],
            widget_property_values: [
              { widget_id: 'addtocart', property_values: [''] },
            ],
          },
          {
            property_name: 'boostWeight',
            property_values: ['0.5'],
            default_values: ['0.5'],
            widget_property_values: [
              { widget_id: 'addtocart', property_values: ['0.5'] },
            ],
          },
        ],
        string_attributes: [],
        localized_string_attributes: [],
        numeric_attributes: [],
        localized_numeric_attributes: [],
        datetime_attributes: [],
        localized_datetime_attributes: [],
        creation_tm: null,
        last_update_tm: null,
        last_update_user: null,
        ab_test: null,
        active: true,
        segment: null,
        advanced_options: null,
      },
      resourceId: 'e567f4b8-6989-6b1e-fef5-ca3b2dd4c9e8',
    },
    {
      lastMove: 'execute',
      name: 'Update',
      initialData: {
        widget_use_case: 'e567f4b8-6989-6b1e-fef5-ca3b2dd4c9e8',
        use_case_id: 'sold_times_v1',
        widget_ids: ['addtocart'],
        name: 'Sold Count',
        category: 'filtering rules',
        tooltip: [
          {
            language: 'en',
            value: 'Filter products by minimum number of times sold.',
          },
        ],
        order: null,
        property_values: [
          {
            property_name: 'min_times_sold',
            property_values: [''],
            default_values: [''],
            widget_property_values: [
              { widget_id: 'addtocart', property_values: [''] },
            ],
          },
          {
            property_name: 'filter_enabled',
            property_values: [''],
            default_values: [''],
            widget_property_values: [
              { widget_id: 'addtocart', property_values: [''] },
            ],
          },
          {
            property_name: 'boostWeight',
            property_values: ['0.5'],
            default_values: ['0.5'],
            widget_property_values: [
              { widget_id: 'addtocart', property_values: ['0.5'] },
            ],
          },
        ],
        string_attributes: [],
        localized_string_attributes: [],
        numeric_attributes: [],
        localized_numeric_attributes: [],
        datetime_attributes: [],
        localized_datetime_attributes: [],
        creation_tm: null,
        last_update_tm: null,
        last_update_user: null,
        ab_test: null,
        active: true,
        segment: null,
        advanced_options: null,
      },
      freshData: {
        widget_use_case: 'e567f4b8-6989-6b1e-fef5-ca3b2dd4c9e8',
        use_case_id: 'sold_times_v1',
        widget_ids: ['addtocart'],
        name: 'Sold Count',
        category: 'filtering rules',
        tooltip: [
          {
            language: 'en',
            value: 'Filter products by minimum number of times sold.',
          },
        ],
        order: null,
        property_values: [
          {
            property_name: 'min_times_sold',
            property_values: [''],
            default_values: [''],
            widget_property_values: [
              { widget_id: 'addtocart', property_values: [''] },
            ],
          },
          {
            property_name: 'filter_enabled',
            property_values: [''],
            default_values: [''],
            widget_property_values: [
              { widget_id: 'addtocart', property_values: [''] },
            ],
          },
          {
            property_name: 'boostWeight',
            property_values: ['0.5'],
            default_values: ['0.5'],
            widget_property_values: [
              { widget_id: 'addtocart', property_values: ['0.5'] },
            ],
          },
        ],
        string_attributes: [],
        localized_string_attributes: [],
        numeric_attributes: [],
        localized_numeric_attributes: [],
        datetime_attributes: [],
        localized_datetime_attributes: [],
        creation_tm: null,
        last_update_tm: null,
        last_update_user: null,
        ab_test: null,
        active: false,
        segment: null,
        advanced_options: null,
      },
    },
    {
      lastMove: 'execute',
      name: 'Create',
      payload: {
        widget_use_case: '728efb2b-3591-4a41-8e3f-8017abc02499',
        use_case_id: 'search_term_segmented_click_purchase_statistics_v1',
        widget_ids: ['addtocart'],
        name: 'Search-Term Segmented Click-Purchase Statistics',
        category: 'sales',
        tooltip: [
          {
            language: 'en',
            value: 'Statistics of click-to-purchase segmented by search term.',
          },
        ],
        order: null,
        property_values: [
          {
            property_name: 'time_range',
            property_values: [''],
            default_values: [''],
            widget_property_values: [
              { widget_id: 'addtocart', property_values: [''] },
            ],
          },
          {
            property_name: 'statistic_type',
            property_values: [''],
            default_values: [''],
            widget_property_values: [
              { widget_id: 'addtocart', property_values: [''] },
            ],
          },
          {
            property_name: 'boostWeight',
            property_values: ['0.5'],
            default_values: ['0.5'],
            widget_property_values: [
              {
                widget_id: 'addtocart',
                property_values: ['0.8267973856209154'],
              },
            ],
          },
        ],
        string_attributes: [],
        localized_string_attributes: [],
        numeric_attributes: [],
        localized_numeric_attributes: [],
        datetime_attributes: [],
        localized_datetime_attributes: [],
        creation_tm: '2025-07-17T17:09:52.468',
        last_update_tm: null,
        last_update_user: null,
        ab_test: {
          name: 'test_104',
          property_names: ['time_range', 'statistic_type'],
        },
        active: true,
        segment: null,
        advanced_options: null,
      },
      resourceId: 'e5e4cca1-5db2-a618-3618-2e7c3c106362',
    },
    {
      lastMove: 'execute',
      name: 'Update',
      initialData: {
        widget_use_case: '7089eae8-30e8-6dd0-2279-f7d0344f93d4',
        use_case_id: 'top_sellers_v1',
        widget_ids: ['search'],
        name: 'Top Sellers',
        category: 'listing',
        tooltip: [
          {
            language: 'en',
            value: 'List products that sold most in recent weeks.',
          },
        ],
        order: 4,
        property_values: [
          {
            property_name: 'max_weeks_since',
            property_values: [''],
            default_values: [''],
            widget_property_values: [
              { widget_id: 'search', property_values: [''] },
            ],
          },
          {
            property_name: 'filter_enabled',
            property_values: [''],
            default_values: [''],
            widget_property_values: [
              { widget_id: 'search', property_values: [''] },
            ],
          },
          {
            property_name: 'boostWeight',
            property_values: ['0.5'],
            default_values: ['0.5'],
            widget_property_values: [
              { widget_id: 'search', property_values: ['0.8515625'] },
            ],
          },
        ],
        string_attributes: [],
        localized_string_attributes: [],
        numeric_attributes: [],
        localized_numeric_attributes: [],
        datetime_attributes: [],
        localized_datetime_attributes: [],
        creation_tm: '2025-07-08 08:22:18',
        last_update_tm: '2025-07-08 08:22:18',
        last_update_user: 'system',
        ab_test: null,
        active: null,
        segment: null,
        advanced_options: null,
      },
      freshData: {
        widget_use_case: '7089eae8-30e8-6dd0-2279-f7d0344f93d4',
        use_case_id: 'top_sellers_v1',
        widget_ids: ['search'],
        name: 'Top Sellers',
        category: 'listing',
        tooltip: [
          {
            language: 'en',
            value: 'List products that sold most in recent weeks.',
          },
        ],
        order: 4,
        property_values: [
          {
            property_name: 'max_weeks_since',
            property_values: [''],
            default_values: [''],
            widget_property_values: [
              { widget_id: 'search', property_values: [''] },
            ],
          },
          {
            property_name: 'filter_enabled',
            property_values: [''],
            default_values: [''],
            widget_property_values: [
              { widget_id: 'search', property_values: [''] },
            ],
          },
          {
            property_name: 'boostWeight',
            property_values: ['0.5'],
            default_values: ['0.5'],
            widget_property_values: [
              { widget_id: 'search', property_values: ['0.6633986928104578'] },
            ],
          },
        ],
        string_attributes: [],
        localized_string_attributes: [],
        numeric_attributes: [],
        localized_numeric_attributes: [],
        datetime_attributes: [],
        localized_datetime_attributes: [],
        creation_tm: '2025-07-08 08:22:18',
        last_update_tm: '2025-07-08 08:22:18',
        last_update_user: 'system',
        ab_test: null,
        active: null,
        segment: null,
        advanced_options: null,
      },
    },
    {
      lastMove: 'execute',
      name: 'Update',
      initialData: {
        widget_use_case: '7089eae8-30e8-6dd0-2279-f7d0344f93d4',
        use_case_id: 'top_sellers_v1',
        widget_ids: ['search'],
        name: 'Top Sellers',
        category: 'listing',
        tooltip: [
          {
            language: 'en',
            value: 'List products that sold most in recent weeks.',
          },
        ],
        order: 4,
        property_values: [
          {
            property_name: 'max_weeks_since',
            property_values: [''],
            default_values: [''],
            widget_property_values: [
              { widget_id: 'search', property_values: [''] },
            ],
          },
          {
            property_name: 'filter_enabled',
            property_values: [''],
            default_values: [''],
            widget_property_values: [
              { widget_id: 'search', property_values: [''] },
            ],
          },
          {
            property_name: 'boostWeight',
            property_values: ['0.5'],
            default_values: ['0.5'],
            widget_property_values: [
              { widget_id: 'search', property_values: ['0.8515625'] },
            ],
          },
        ],
        string_attributes: [],
        localized_string_attributes: [],
        numeric_attributes: [],
        localized_numeric_attributes: [],
        datetime_attributes: [],
        localized_datetime_attributes: [],
        creation_tm: '2025-07-08 08:22:18',
        last_update_tm: '2025-07-08 08:22:18',
        last_update_user: 'system',
        ab_test: null,
        active: null,
        segment: null,
        advanced_options: null,
      },
      freshData: {
        widget_use_case: '7089eae8-30e8-6dd0-2279-f7d0344f93d4',
        use_case_id: 'top_sellers_v1',
        widget_ids: ['search'],
        name: 'Top Sellers',
        category: 'listing',
        tooltip: [
          {
            language: 'en',
            value: 'List products that sold most in recent weeks.',
          },
        ],
        order: 4,
        property_values: [
          {
            property_name: 'max_weeks_since',
            property_values: [''],
            default_values: [''],
            widget_property_values: [
              { widget_id: 'search', property_values: [''] },
            ],
          },
          {
            property_name: 'filter_enabled',
            property_values: [''],
            default_values: [''],
            widget_property_values: [
              { widget_id: 'search', property_values: [''] },
            ],
          },
          {
            property_name: 'boostWeight',
            property_values: ['0.5'],
            default_values: ['0.5'],
            widget_property_values: [
              { widget_id: 'search', property_values: ['0.44058229352347056'] },
            ],
          },
        ],
        string_attributes: [],
        localized_string_attributes: [],
        numeric_attributes: [],
        localized_numeric_attributes: [],
        datetime_attributes: [],
        localized_datetime_attributes: [],
        creation_tm: '2025-07-08 08:22:18',
        last_update_tm: '2025-07-08 08:22:18',
        last_update_user: 'system',
        ab_test: null,
        active: null,
        segment: null,
        advanced_options: null,
      },
    },
    {
      lastMove: 'execute',
      name: 'Delete',
      resource: {
        widget_use_case: '4ae6c2b1-b8de-b884-8edc-3a6c637e89b0',
        use_case_id: 'search_term_segmented_click_purchase_statistics_v1',
        widget_ids: ['similar_client'],
        name: 'Search-Term Segmented Click-Purchase Statistics',
        category: 'sales',
        tooltip: [
          {
            language: 'en',
            value: 'Statistics of click-to-purchase segmented by search term.',
          },
        ],
        order: null,
        property_values: [
          {
            property_name: 'time_range',
            property_values: [''],
            default_values: [''],
            widget_property_values: [
              { widget_id: 'similar_client', property_values: ['all_time'] },
            ],
          },
          {
            property_name: 'statistic_type',
            property_values: [''],
            default_values: [''],
            widget_property_values: [
              { widget_id: 'similar_client', property_values: [''] },
            ],
          },
          {
            property_name: 'boostWeight',
            property_values: ['0.5'],
            default_values: ['0.5'],
            widget_property_values: [
              {
                widget_id: 'similar_client',
                property_values: ['0.6911764705882355'],
              },
            ],
          },
        ],
        string_attributes: [],
        localized_string_attributes: [],
        numeric_attributes: [],
        localized_numeric_attributes: [],
        datetime_attributes: [],
        localized_datetime_attributes: [],
        creation_tm: '2025-07-15 16:14:38',
        last_update_tm: null,
        last_update_user: null,
        ab_test: {
          name: 'test_103',
          property_names: ['time_range', 'statistic_type'],
        },
        active: true,
        segment: null,
        advanced_options: null,
      },
    },
    {
      lastMove: 'execute',
      name: 'Create',
      payload: {
        widget_use_case: 'a3b9ef92-dfcc-4958-b7fc-244f632064f4',
        use_case_id: 'personalization_prior_purchases_expand_v1',
        widget_ids: ['addtocart'],
        name: 'Personalization on Prior Purchases: Expand',
        category: 'personalization',
        tooltip: [
          {
            language: 'en',
            value: 'Expand product selection based on previous purchases.',
          },
        ],
        order: null,
        property_values: [
          {
            property_name: 'algorithm',
            property_values: [''],
            default_values: [''],
            widget_property_values: [
              { widget_id: 'addtocart', property_values: [''] },
            ],
          },
          {
            property_name: 'boostWeight',
            property_values: ['0.5'],
            default_values: ['0.5'],
            widget_property_values: [
              { widget_id: 'addtocart', property_values: ['0.5'] },
            ],
          },
        ],
        string_attributes: [],
        localized_string_attributes: [],
        numeric_attributes: [],
        localized_numeric_attributes: [],
        datetime_attributes: [],
        localized_datetime_attributes: [],
        creation_tm: null,
        last_update_tm: null,
        last_update_user: null,
        ab_test: null,
        active: true,
        segment: null,
        advanced_options: null,
      },
      resourceId: '92b622ea-eda2-0e90-5dd6-e9eb9de27217',
    },
    {
      lastMove: 'execute',
      name: 'Update',
      initialData: {
        widget_use_case: '33e0fca9-4c4d-4a40-0474-b2d5b27f2a41',
        use_case_id: 'similar_items_v1',
        widget_ids: ['related', 'basket'],
        name: 'Similar Items',
        category: 'personalization',
        tooltip: [
          {
            language: 'en',
            value: 'Filter or suggest items similar to a reference item.',
          },
        ],
        order: null,
        property_values: [
          {
            property_name: 'algorithm',
            property_values: [''],
            default_values: [''],
            widget_property_values: [
              { widget_id: 'related', property_values: [''] },
              { widget_id: 'basket', property_values: [''] },
            ],
          },
          {
            property_name: 'filter_enabled',
            property_values: [''],
            default_values: [''],
            widget_property_values: [
              { widget_id: 'related', property_values: [''] },
              { widget_id: 'basket', property_values: [''] },
            ],
          },
          {
            property_name: 'boostWeight',
            property_values: ['0.5'],
            default_values: ['0.5'],
            widget_property_values: [
              { widget_id: 'related', property_values: ['0.5'] },
              { widget_id: 'basket', property_values: ['0.5'] },
            ],
          },
        ],
        string_attributes: [],
        localized_string_attributes: [],
        numeric_attributes: [],
        localized_numeric_attributes: [],
        datetime_attributes: [],
        localized_datetime_attributes: [],
        creation_tm: '2025-07-17 13:09:21',
        last_update_tm: null,
        last_update_user: null,
        ab_test: {
          name: 'test_ddd',
          property_names: ['algorithm', 'filter_enabled'],
        },
        active: true,
        segment: null,
        advanced_options: null,
      },
      freshData: {
        widget_use_case: '33e0fca9-4c4d-4a40-0474-b2d5b27f2a41',
        use_case_id: 'similar_items_v1',
        widget_ids: ['related', 'basket'],
        name: 'Similar Items',
        category: 'personalization',
        tooltip: [
          {
            language: 'en',
            value: 'Filter or suggest items similar to a reference item.',
          },
        ],
        order: null,
        property_values: [
          {
            property_name: 'algorithm',
            property_values: ['brand'],
            default_values: [''],
            widget_property_values: [
              { widget_id: 'related', property_values: ['category'] },
              { widget_id: 'basket', property_values: [''] },
            ],
          },
          {
            property_name: 'filter_enabled',
            property_values: [''],
            default_values: [''],
            widget_property_values: [
              { widget_id: 'related', property_values: [''] },
              { widget_id: 'basket', property_values: [''] },
            ],
          },
          {
            property_name: 'boostWeight',
            property_values: ['0.5'],
            default_values: ['0.5'],
            widget_property_values: [
              { widget_id: 'related', property_values: ['0.5'] },
              { widget_id: 'basket', property_values: ['0.5'] },
            ],
          },
        ],
        string_attributes: [],
        localized_string_attributes: [],
        numeric_attributes: [],
        localized_numeric_attributes: [],
        datetime_attributes: [],
        localized_datetime_attributes: [],
        creation_tm: '2025-07-17 13:09:21',
        last_update_tm: null,
        last_update_user: null,
        ab_test: {
          name: 'test_ddd',
          property_names: ['algorithm', 'filter_enabled'],
        },
        active: true,
        segment: null,
        advanced_options: null,
      },
    },
  ],
  cursor: 8,
};
