export default {
  success: true,
  status: 'SUCCESS',
  code: 200,
  payload: [
    {
      narrative_id: 'basket',
      name: 'basket',
      tooltip: [
        {
          language: 'en',
          value: 'some tooltip',
        },
      ],
      page_id: 'basket',
      order: 2,
      string_attributes: [],
      localized_string_attributes: [],
      numeric_attributes: [],
      localized_numeric_attributes: [],
      datetime_attributes: [],
      localized_datetime_attributes: [],
      creation_tm: '2025-05-06 12:40:01',
      last_update_tm: '2025-05-06 12:40:01',
      last_update_user: 'system',
    },
    {
      narrative_id: 'pdp',
      name: 'pdp',
      tooltip: [
        {
          language: 'en',
          value: 'some tooltip',
        },
      ],
      page_id: 'pdp',
      order: 3,
      string_attributes: [],
      localized_string_attributes: [],
      numeric_attributes: [],
      localized_numeric_attributes: [],
      datetime_attributes: [],
      localized_datetime_attributes: [],
      creation_tm: '2025-05-06 12:40:01',
      last_update_tm: '2025-05-06 12:40:01',
      last_update_user: 'system',
    },
    {
      narrative_id: 'basket-overlay',
      name: 'basket-overlay',
      tooltip: [
        {
          language: 'en',
          value: 'some tooltip',
        },
      ],
      page_id: 'basket',
      order: 4,
      string_attributes: [],
      localized_string_attributes: [],
      numeric_attributes: [],
      localized_numeric_attributes: [],
      datetime_attributes: [],
      localized_datetime_attributes: [],
      creation_tm: '2025-05-06 12:40:01',
      last_update_tm: '2025-05-06 12:40:01',
      last_update_user: 'system',
    },
    {
      narrative_id: 'search',
      name: 'search',
      tooltip: [
        {
          language: 'en',
          value: 'some tooltip',
        },
      ],
      page_id: 'search',
      order: 1,
      string_attributes: [],
      localized_string_attributes: [],
      numeric_attributes: [],
      localized_numeric_attributes: [],
      datetime_attributes: [],
      localized_datetime_attributes: [],
      creation_tm: '2025-05-06 12:40:01',
      last_update_tm: '2025-05-06 12:40:01',
      last_update_user: 'system',
    },
  ],
  tm: '20250624123819',
  errors: [],
};
