export default {
  success: true,
  status: 'SUCCESS',
  code: 200,
  payload: [
    {
      page_id: 'navigation',
      name: 'navigation',
      tooltip: [
        {
          language: 'en',
          value: 'Category Page',
        },
      ],
      order: 2,
      type: 'listing',
      string_attributes: [],
      localized_string_attributes: [],
      numeric_attributes: [],
      localized_numeric_attributes: [],
      datetime_attributes: [],
      localized_datetime_attributes: [],
      creation_tm: '2025-05-06 12:40:01',
      last_update_tm: '2025-05-06 12:40:01',
      last_update_user: 'system',
    },
    {
      page_id: 'search',
      name: 'search',
      tooltip: [
        {
          language: 'en',
          value: 'Search-As-You-Type (and result page)',
        },
      ],
      order: 1,
      type: 'listing',
      string_attributes: [],
      localized_string_attributes: [],
      numeric_attributes: [],
      localized_numeric_attributes: [],
      datetime_attributes: [],
      localized_datetime_attributes: [],
      creation_tm: '2025-05-06 12:40:01',
      last_update_tm: '2025-05-06 12:40:01',
      last_update_user: 'system',
    },
    {
      page_id: 'pdp',
      name: 'pdp',
      tooltip: [
        {
          language: 'en',
          value: 'Product Detail Page',
        },
      ],
      order: 3,
      type: 'item',
      string_attributes: [],
      localized_string_attributes: [],
      numeric_attributes: [],
      localized_numeric_attributes: [],
      datetime_attributes: [],
      localized_datetime_attributes: [],
      creation_tm: '2025-05-06 12:40:01',
      last_update_tm: '2025-05-06 12:40:01',
      last_update_user: 'system',
    },
    {
      page_id: 'basket',
      name: 'basket',
      tooltip: [
        {
          language: 'en',
          value: 'Basket (overlay and page)',
        },
      ],
      order: 4,
      type: 'item',
      string_attributes: [],
      localized_string_attributes: [],
      numeric_attributes: [],
      localized_numeric_attributes: [],
      datetime_attributes: [],
      localized_datetime_attributes: [],
      creation_tm: '2025-05-06 12:40:01',
      last_update_tm: '2025-05-06 12:40:01',
      last_update_user: 'system',
    },
    {
      page_id: 'home',
      name: 'home',
      tooltip: [
        {
          language: 'en',
          value: 'Home Page',
        },
      ],
      order: 0,
      type: 'home',
      string_attributes: [],
      localized_string_attributes: [],
      numeric_attributes: [],
      localized_numeric_attributes: [],
      datetime_attributes: [],
      localized_datetime_attributes: [],
      creation_tm: '2025-05-06 12:40:01',
      last_update_tm: '2025-05-06 12:40:01',
      last_update_user: 'system',
    },
  ],
  tm: '20250624123819',
  errors: [],
};
