export default {
  success: true,
  status: 'SUCCESS',
  code: 200,
  payload: [
    {
      widget_id: 'basket_client',
      name: 'basket_client',
      tooltip: [
        {
          language: 'en',
          value: 'some tooltip',
        },
      ],
      narrative_id: 'basket',
      order: 2,
      string_attributes: [],
      localized_string_attributes: [],
      numeric_attributes: [],
      localized_numeric_attributes: [],
      datetime_attributes: [],
      localized_datetime_attributes: [],
      creation_tm: '2025-05-06 12:40:01',
      last_update_tm: '2025-05-06 12:40:01',
      last_update_user: 'system',
    },
    {
      widget_id: 'search',
      name: 'search',
      tooltip: [
        {
          language: 'en',
          value: 'some tooltip',
        },
      ],
      narrative_id: 'search',
      order: 3,
      string_attributes: [],
      localized_string_attributes: [],
      numeric_attributes: [],
      localized_numeric_attributes: [],
      datetime_attributes: [],
      localized_datetime_attributes: [],
      creation_tm: '2025-05-06 12:40:01',
      last_update_tm: '2025-05-06 12:40:01',
      last_update_user: 'system',
    },
    {
      widget_id: 'basket',
      name: 'basket',
      tooltip: [
        {
          language: 'en',
          value: 'some tooltip',
        },
      ],
      narrative_id: 'basket',
      order: 7,
      string_attributes: [],
      localized_string_attributes: [],
      numeric_attributes: [],
      localized_numeric_attributes: [],
      datetime_attributes: [],
      localized_datetime_attributes: [],
      creation_tm: '2025-05-06 12:40:01',
      last_update_tm: '2025-05-06 12:40:01',
      last_update_user: 'system',
    },
    {
      widget_id: 'addtocart',
      name: 'addtocart',
      tooltip: [
        {
          language: 'en',
          value: 'some tooltip',
        },
      ],
      narrative_id: 'basket-overlay',
      order: 8,
      string_attributes: [],
      localized_string_attributes: [],
      numeric_attributes: [],
      localized_numeric_attributes: [],
      datetime_attributes: [],
      localized_datetime_attributes: [],
      creation_tm: '2025-05-06 12:40:01',
      last_update_tm: '2025-05-06 12:40:01',
      last_update_user: 'system',
    },
    {
      widget_id: 'similar_client',
      name: 'similar_client',
      tooltip: [
        {
          language: 'en',
          value: 'some tooltip',
        },
      ],
      narrative_id: 'pdp',
      order: 1,
      string_attributes: [],
      localized_string_attributes: [],
      numeric_attributes: [],
      localized_numeric_attributes: [],
      datetime_attributes: [],
      localized_datetime_attributes: [],
      creation_tm: '2025-05-06 12:40:01',
      last_update_tm: '2025-05-06 12:40:01',
      last_update_user: 'system',
    },
    {
      widget_id: 'navigation',
      name: 'navigation',
      tooltip: [
        {
          language: 'en',
          value: 'some tooltip',
        },
      ],
      narrative_id: 'home',
      order: 4,
      string_attributes: [],
      localized_string_attributes: [],
      numeric_attributes: [],
      localized_numeric_attributes: [],
      datetime_attributes: [],
      localized_datetime_attributes: [],
      creation_tm: '2025-05-06 12:40:01',
      last_update_tm: '2025-05-06 12:40:01',
      last_update_user: 'system',
    },
    {
      widget_id: 'similar',
      name: 'similar',
      tooltip: [
        {
          language: 'en',
          value: 'some tooltip',
        },
      ],
      narrative_id: 'pdp',
      order: 5,
      string_attributes: [],
      localized_string_attributes: [],
      numeric_attributes: [],
      localized_numeric_attributes: [],
      datetime_attributes: [],
      localized_datetime_attributes: [],
      creation_tm: '2025-05-06 12:40:01',
      last_update_tm: '2025-05-06 12:40:01',
      last_update_user: 'system',
    },
    {
      widget_id: 'related',
      name: 'related',
      tooltip: [
        {
          language: 'en',
          value: 'some tooltip',
        },
      ],
      narrative_id: 'pdp',
      order: 6,
      string_attributes: [],
      localized_string_attributes: [],
      numeric_attributes: [],
      localized_numeric_attributes: [],
      datetime_attributes: [],
      localized_datetime_attributes: [],
      creation_tm: '2025-05-06 12:40:01',
      last_update_tm: '2025-05-06 12:40:01',
      last_update_user: 'system',
    },
  ],
  tm: '20250624132041',
  errors: [],
};
