export default {
  success: true,
  status: 'SUCCESS',
  code: 200,
  payload: [
    {
      widget_use_case: '1',
      use_case_id: '7',
      widget_ids: ['widget_12'],
      name: '',
      tooltip: [
        {
          language: 'en',
          value: 'Scores items based on matching scorer terms in the search.',
        },
      ],
      order: 0,
      property_values: [
        {
          property_name: '',
          property_values: [''],
          default_values: [''],
          widget_property_values: [
            {
              widget_id: 'widget_12',
              property_values: [''],
            },
          ],
          tooltip: [
            {
              language: 'en',
              value:
                'Scores items based on matching scorer terms in the search.',
            },
          ],
          string_attributes: [],
          localized_string_attributes: [],
          numeric_attributes: [],
          localized_numeric_attributes: [],
          datetime_attributes: [],
          localized_datetime_attributes: [],
        },
      ],
      string_attributes: [],
      localized_string_attributes: [],
      numeric_attributes: [],
      localized_numeric_attributes: [],
      datetime_attributes: [],
      localized_datetime_attributes: [],
      creation_tm: '2025-04-04 04:15:39',
      last_update_tm: '2025-04-04 04:15:39',
      last_update_user: 'system',
      category: '',
    },
    {
      widget_use_case: '1',
      use_case_id: '10',
      widget_ids: ['widget_12'],
      name: '',
      tooltip: [
        {
          language: 'en',
          value: 'Sets the search mode (e.g., semantic, keyword).',
        },
      ],
      order: 0,
      property_values: [
        {
          property_name: '',
          property_values: [''],
          default_values: [''],
          widget_property_values: [
            {
              widget_id: 'widget_12',
              property_values: [''],
            },
          ],
          tooltip: [
            {
              language: 'en',
              value: 'Sets the search mode (e.g., semantic, keyword).',
            },
          ],
          string_attributes: [],
          localized_string_attributes: [],
          numeric_attributes: [],
          localized_numeric_attributes: [],
          datetime_attributes: [],
          localized_datetime_attributes: [],
        },
      ],
      string_attributes: [],
      localized_string_attributes: [],
      numeric_attributes: [],
      localized_numeric_attributes: [],
      datetime_attributes: [],
      localized_datetime_attributes: [],
      creation_tm: '2025-04-04 13:45:03',
      last_update_tm: '2025-04-04 13:45:03',
      last_update_user: 'system',
      category: '',
    },
    {
      widget_use_case: '1',
      use_case_id: '21',
      widget_ids: ['widget_12'],
      name: '',
      tooltip: [
        {
          language: 'en',
          value: 'Removes the search functionality from the page.',
        },
      ],
      order: 0,
      property_values: [
        {
          property_name: '',
          property_values: [''],
          default_values: [''],
          widget_property_values: [
            {
              widget_id: 'widget_12',
              property_values: [''],
            },
          ],
          tooltip: [
            {
              language: 'en',
              value: 'Removes the search functionality from the page.',
            },
          ],
          string_attributes: [],
          localized_string_attributes: [],
          numeric_attributes: [],
          localized_numeric_attributes: [],
          datetime_attributes: [],
          localized_datetime_attributes: [],
        },
      ],
      string_attributes: [],
      localized_string_attributes: [],
      numeric_attributes: [],
      localized_numeric_attributes: [],
      datetime_attributes: [],
      localized_datetime_attributes: [],
      creation_tm: '2025-04-04 13:45:03',
      last_update_tm: '2025-04-04 13:45:03',
      last_update_user: 'system',
      category: '',
    },
    {
      widget_use_case: '1',
      use_case_id: '11',
      widget_ids: ['widget_12'],
      name: '',
      tooltip: [
        {
          language: 'en',
          value: 'Sets the relaxation mode for search queries.',
        },
      ],
      order: 0,
      property_values: [
        {
          property_name: '',
          property_values: [''],
          default_values: [''],
          widget_property_values: [
            {
              widget_id: 'widget_12',
              property_values: [''],
            },
          ],
          tooltip: [
            {
              language: 'en',
              value: 'Sets the relaxation mode for search queries.',
            },
          ],
          string_attributes: [],
          localized_string_attributes: [],
          numeric_attributes: [],
          localized_numeric_attributes: [],
          datetime_attributes: [],
          localized_datetime_attributes: [],
        },
      ],
      string_attributes: [],
      localized_string_attributes: [],
      numeric_attributes: [],
      localized_numeric_attributes: [],
      datetime_attributes: [],
      localized_datetime_attributes: [],
      creation_tm: '2025-04-04 13:45:03',
      last_update_tm: '2025-04-04 13:45:03',
      last_update_user: 'system',
      category: '',
    },
    {
      widget_use_case: '1',
      use_case_id: '8',
      widget_ids: ['widget_12'],
      name: '',
      tooltip: [
        {
          language: 'en',
          value: 'Scores items based on the search term in the title.',
        },
      ],
      order: 0,
      property_values: [
        {
          property_name: '',
          property_values: [''],
          default_values: [''],
          widget_property_values: [
            {
              widget_id: 'widget_12',
              property_values: [''],
            },
          ],
          tooltip: [
            {
              language: 'en',
              value: 'Scores items based on the search term in the title.',
            },
          ],
          string_attributes: [],
          localized_string_attributes: [],
          numeric_attributes: [],
          localized_numeric_attributes: [],
          datetime_attributes: [],
          localized_datetime_attributes: [],
        },
      ],
      string_attributes: [],
      localized_string_attributes: [],
      numeric_attributes: [],
      localized_numeric_attributes: [],
      datetime_attributes: [],
      localized_datetime_attributes: [],
      creation_tm: '2025-04-04 16:22:40',
      last_update_tm: '2025-04-04 16:22:40',
      last_update_user: 'system',
      category: '',
    },
    {
      widget_use_case: '1',
      use_case_id: '8',
      widget_ids: ['widget_12'],
      name: '',
      tooltip: [
        {
          language: 'en',
          value: 'Scores items based on the search term in the title.',
        },
      ],
      order: 0,
      property_values: [
        {
          property_name: '',
          property_values: [''],
          default_values: [''],
          widget_property_values: [
            {
              widget_id: 'widget_12',
              property_values: [''],
            },
          ],
          tooltip: [
            {
              language: 'en',
              value: 'Scores items based on the search term in the title.',
            },
          ],
          string_attributes: [],
          localized_string_attributes: [],
          numeric_attributes: [],
          localized_numeric_attributes: [],
          datetime_attributes: [],
          localized_datetime_attributes: [],
        },
      ],
      string_attributes: [],
      localized_string_attributes: [],
      numeric_attributes: [],
      localized_numeric_attributes: [],
      datetime_attributes: [],
      localized_datetime_attributes: [],
      creation_tm: '2025-04-04 16:26:15',
      last_update_tm: '2025-04-04 16:26:15',
      last_update_user: 'system',
      category: '',
    },
    {
      widget_use_case: '1',
      use_case_id: '10',
      widget_ids: ['widget_13'],
      name: '',
      tooltip: [
        {
          language: 'en',
          value: 'Sets the search mode (e.g., semantic, keyword).',
        },
      ],
      order: 0,
      property_values: [
        {
          property_name: '',
          property_values: [''],
          default_values: [''],
          widget_property_values: [
            {
              widget_id: 'widget_13',
              property_values: [''],
            },
          ],
          tooltip: [
            {
              language: 'en',
              value: 'Sets the search mode (e.g., semantic, keyword).',
            },
          ],
          string_attributes: [],
          localized_string_attributes: [],
          numeric_attributes: [],
          localized_numeric_attributes: [],
          datetime_attributes: [],
          localized_datetime_attributes: [],
        },
      ],
      string_attributes: [],
      localized_string_attributes: [],
      numeric_attributes: [],
      localized_numeric_attributes: [],
      datetime_attributes: [],
      localized_datetime_attributes: [],
      creation_tm: '2025-04-04 16:27:30',
      last_update_tm: '2025-04-04 16:27:30',
      last_update_user: 'system',
      category: '',
    },
    {
      widget_use_case: '1',
      use_case_id: '20',
      widget_ids: ['widget_12'],
      name: '',
      tooltip: [
        {
          language: 'en',
          value: 'Scores items based on a fixed content order.',
        },
      ],
      order: 0,
      property_values: [
        {
          property_name: '',
          property_values: [''],
          default_values: [''],
          widget_property_values: [
            {
              widget_id: 'widget_12',
              property_values: [''],
            },
          ],
          tooltip: [
            {
              language: 'en',
              value: 'Scores items based on a fixed content order.',
            },
          ],
          string_attributes: [],
          localized_string_attributes: [],
          numeric_attributes: [],
          localized_numeric_attributes: [],
          datetime_attributes: [],
          localized_datetime_attributes: [],
        },
      ],
      string_attributes: [],
      localized_string_attributes: [],
      numeric_attributes: [],
      localized_numeric_attributes: [],
      datetime_attributes: [],
      localized_datetime_attributes: [],
      creation_tm: '2025-04-04 16:27:30',
      last_update_tm: '2025-04-04 16:27:30',
      last_update_user: 'system',
      category: '',
    },
    {
      widget_use_case: '1',
      use_case_id: '4',
      widget_ids: ['widget_12'],
      name: '',
      tooltip: [
        {
          language: 'en',
          value: 'Scores items based on the search term in the body.',
        },
      ],
      order: 0,
      property_values: [
        {
          property_name: '',
          property_values: [''],
          default_values: [''],
          widget_property_values: [
            {
              widget_id: 'widget_12',
              property_values: [''],
            },
          ],
          tooltip: [
            {
              language: 'en',
              value: 'Scores items based on the search term in the body.',
            },
          ],
          string_attributes: [],
          localized_string_attributes: [],
          numeric_attributes: [],
          localized_numeric_attributes: [],
          datetime_attributes: [],
          localized_datetime_attributes: [],
        },
      ],
      string_attributes: [],
      localized_string_attributes: [],
      numeric_attributes: [],
      localized_numeric_attributes: [],
      datetime_attributes: [],
      localized_datetime_attributes: [],
      creation_tm: '2025-04-04 19:30:25',
      last_update_tm: '2025-04-04 19:30:25',
      last_update_user: 'system',
      category: '',
    },
    {
      widget_use_case: '1',
      use_case_id: '13',
      widget_ids: ['widget_12'],
      name: '',
      tooltip: [
        {
          language: 'en',
          value:
            'Scores items based on customer journey prediction embeddings.',
        },
      ],
      order: 0,
      property_values: [
        {
          property_name: '',
          property_values: [''],
          default_values: [''],
          widget_property_values: [
            {
              widget_id: 'widget_12',
              property_values: [''],
            },
          ],
          tooltip: [
            {
              language: 'en',
              value:
                'Scores items based on customer journey prediction embeddings.',
            },
          ],
          string_attributes: [],
          localized_string_attributes: [],
          numeric_attributes: [],
          localized_numeric_attributes: [],
          datetime_attributes: [],
          localized_datetime_attributes: [],
        },
      ],
      string_attributes: [],
      localized_string_attributes: [],
      numeric_attributes: [],
      localized_numeric_attributes: [],
      datetime_attributes: [],
      localized_datetime_attributes: [],
      creation_tm: '2025-04-08 16:10:00',
      last_update_tm: '2025-04-08 16:10:00',
      last_update_user: 'system',
      category: '',
    },
    {
      widget_use_case: '1',
      use_case_id: '17',
      widget_ids: ['widget_12'],
      name: '',
      tooltip: [
        {
          language: 'en',
          value: 'Ranks items for cross-selling based on embeddings.',
        },
      ],
      order: 0,
      property_values: [
        {
          property_name: '',
          property_values: [''],
          default_values: [''],
          widget_property_values: [
            {
              widget_id: 'widget_12',
              property_values: [''],
            },
          ],
          tooltip: [
            {
              language: 'en',
              value: 'Ranks items for cross-selling based on embeddings.',
            },
          ],
          string_attributes: [],
          localized_string_attributes: [],
          numeric_attributes: [],
          localized_numeric_attributes: [],
          datetime_attributes: [],
          localized_datetime_attributes: [],
        },
      ],
      string_attributes: [],
      localized_string_attributes: [],
      numeric_attributes: [],
      localized_numeric_attributes: [],
      datetime_attributes: [],
      localized_datetime_attributes: [],
      creation_tm: '2025-04-16 12:36:29',
      last_update_tm: '2025-04-16 12:36:29',
      last_update_user: 'system',
      category: '',
    },
    {
      widget_use_case: '1',
      use_case_id: '21',
      widget_ids: ['widget_10', 'widget_12'],
      name: '',
      tooltip: [
        {
          language: 'en',
          value: '[updated] Sets the search mode (e.g., semantic, keyword).',
        },
      ],
      order: 0,
      property_values: [
        {
          property_name: '',
          property_values: [''],
          default_values: [''],
          widget_property_values: [
            {
              widget_id: 'widget_10',
              property_values: [''],
            },
          ],
          tooltip: [
            {
              language: 'en',
              value:
                '[updated] Sets the search mode (e.g., semantic, keyword).',
            },
          ],
          string_attributes: [],
          localized_string_attributes: [],
          numeric_attributes: [],
          localized_numeric_attributes: [],
          datetime_attributes: [],
          localized_datetime_attributes: [],
        },
      ],
      string_attributes: [],
      localized_string_attributes: [],
      numeric_attributes: [],
      localized_numeric_attributes: [],
      datetime_attributes: [],
      localized_datetime_attributes: [],
      creation_tm: '2025-05-02 14:45:20',
      last_update_tm: '2025-05-02 14:45:20',
      last_update_user: 'dana.negrescu@boxalino.com',
      category: '',
    },
    {
      widget_use_case: '1f8969eb-47c3-e343-e6dc-9abbe94c95c8',
      use_case_id: 'search_fields_v1',
      widget_ids: ['similar_client'],
      name: 'Search Fields',
      tooltip: [
        {
          language: 'en',
          value: 'Select which fields to include in search.',
        },
      ],
      order: 26,
      property_values: [
        {
          property_name: 'search_fields',
          property_values: [''],
          default_values: ['category'],
          widget_property_values: [
            {
              widget_id: 'similar_client',
              property_values: ['category'],
            },
          ],
          tooltip: [],
          string_attributes: [],
          localized_string_attributes: [],
          numeric_attributes: [],
          localized_numeric_attributes: [],
          datetime_attributes: [],
          localized_datetime_attributes: [],
        },
        {
          property_name: 'boostWeight',
          property_values: ['0.5'],
          default_values: ['0.5'],
          widget_property_values: [
            {
              widget_id: 'similar_client',
              property_values: ['0.8'],
            },
          ],
          tooltip: [],
          string_attributes: [],
          localized_string_attributes: [],
          numeric_attributes: [],
          localized_numeric_attributes: [],
          datetime_attributes: [],
          localized_datetime_attributes: [],
        },
      ],
      string_attributes: [],
      localized_string_attributes: [],
      numeric_attributes: [],
      localized_numeric_attributes: [],
      datetime_attributes: [],
      localized_datetime_attributes: [],
      creation_tm: '2025-05-29 08:12:49',
      last_update_tm: '2025-05-29 08:12:58',
      last_update_user: 'system',
      category: 'filtering rules',
    },
    {
      widget_use_case: 'b9991a14-7783-d7da-a3b3-6ec3bfcd2ba2',
      use_case_id: 'stock_v1',
      widget_ids: ['similar_client', 'similar'],
      name: 'Stock of a Product',
      tooltip: [
        {
          language: 'en',
          value: 'Filter or highlight products based on minimum stock level.',
        },
      ],
      order: 0,
      property_values: [
        {
          property_name: 'min_stock',
          property_values: [''],
          default_values: [''],
          widget_property_values: [
            {
              widget_id: 'similar_client',
              property_values: [''],
            },
            {
              widget_id: 'similar',
              property_values: [''],
            },
          ],
          tooltip: [],
          string_attributes: [],
          localized_string_attributes: [],
          numeric_attributes: [],
          localized_numeric_attributes: [],
          datetime_attributes: [],
          localized_datetime_attributes: [],
        },
        {
          property_name: 'boostWeight',
          property_values: ['0.5'],
          default_values: ['0.5'],
          widget_property_values: [
            {
              widget_id: 'similar_client',
              property_values: ['0.5'],
            },
            {
              widget_id: 'similar',
              property_values: ['0.5'],
            },
          ],
          tooltip: [],
          string_attributes: [],
          localized_string_attributes: [],
          numeric_attributes: [],
          localized_numeric_attributes: [],
          datetime_attributes: [],
          localized_datetime_attributes: [],
        },
        {
          property_name: 'filter_enabled',
          property_values: [''],
          default_values: ['false'],
          widget_property_values: [
            {
              widget_id: 'similar_client',
              property_values: ['true'],
            },
            {
              widget_id: 'similar',
              property_values: ['false'],
            },
          ],
          tooltip: [],
          string_attributes: [],
          localized_string_attributes: [],
          numeric_attributes: [],
          localized_numeric_attributes: [],
          datetime_attributes: [],
          localized_datetime_attributes: [],
        },
      ],
      string_attributes: [],
      localized_string_attributes: [],
      numeric_attributes: [],
      localized_numeric_attributes: [],
      datetime_attributes: [],
      localized_datetime_attributes: [],
      creation_tm: '2025-05-29 10:05:04',
      last_update_tm: '2025-05-30 15:40:39',
      last_update_user: 'system',
      category: 'filtering rules',
    },
    {
      widget_use_case: '2befc21d-7c98-5d17-c32b-6a253c5a4ee3',
      use_case_id: 'price_v1',
      widget_ids: ['search'],
      name: 'Price Range',
      tooltip: [
        {
          language: 'en',
          value: 'Filter products based on minimum price.',
        },
      ],
      order: 6,
      property_values: [
        {
          property_name: 'filter_enabled',
          property_values: [''],
          default_values: [''],
          widget_property_values: [
            {
              widget_id: 'search',
              property_values: [''],
            },
          ],
          tooltip: [],
          string_attributes: [],
          localized_string_attributes: [],
          numeric_attributes: [],
          localized_numeric_attributes: [],
          datetime_attributes: [],
          localized_datetime_attributes: [],
        },
        {
          property_name: 'boostWeight',
          property_values: ['0.5'],
          default_values: ['0.5'],
          widget_property_values: [
            {
              widget_id: 'search',
              property_values: ['0.5'],
            },
          ],
          tooltip: [],
          string_attributes: [],
          localized_string_attributes: [],
          numeric_attributes: [],
          localized_numeric_attributes: [],
          datetime_attributes: [],
          localized_datetime_attributes: [],
        },
        {
          property_name: 'min_price',
          property_values: [''],
          default_values: ['30'],
          widget_property_values: [
            {
              widget_id: 'search',
              property_values: ['30'],
            },
          ],
          tooltip: [],
          string_attributes: [],
          localized_string_attributes: [],
          numeric_attributes: [],
          localized_numeric_attributes: [],
          datetime_attributes: [],
          localized_datetime_attributes: [],
        },
      ],
      string_attributes: [],
      localized_string_attributes: [],
      numeric_attributes: [],
      localized_numeric_attributes: [],
      datetime_attributes: [],
      localized_datetime_attributes: [],
      creation_tm: '2025-05-30 16:03:28',
      last_update_tm: '2025-05-30 16:03:28',
      last_update_user: 'system',
      category: 'filtering rules',
    },
    {
      widget_use_case: '3a4c690e-0299-7358-1bc1-8038a4c2a201',
      use_case_id: 'bought_together_v1',
      widget_ids: ['search'],
      name: 'Bought Together',
      tooltip: [
        {
          language: 'en',
          value: 'Suggest products frequently bought together.',
        },
      ],
      order: 33,
      property_values: [
        {
          property_name: 'boostWeight',
          property_values: ['0.5'],
          default_values: ['0.5'],
          widget_property_values: [
            {
              widget_id: 'search',
              property_values: ['0.6'],
            },
          ],
          tooltip: [],
          string_attributes: [],
          localized_string_attributes: [],
          numeric_attributes: [],
          localized_numeric_attributes: [],
          datetime_attributes: [],
          localized_datetime_attributes: [],
        },
        {
          property_name: 'enabled',
          property_values: [''],
          default_values: ['false'],
          widget_property_values: [
            {
              widget_id: 'search',
              property_values: ['false'],
            },
          ],
          tooltip: [],
          string_attributes: [],
          localized_string_attributes: [],
          numeric_attributes: [],
          localized_numeric_attributes: [],
          datetime_attributes: [],
          localized_datetime_attributes: [],
        },
      ],
      string_attributes: [],
      localized_string_attributes: [],
      numeric_attributes: [],
      localized_numeric_attributes: [],
      datetime_attributes: [],
      localized_datetime_attributes: [],
      creation_tm: '2025-05-20 06:16:24',
      last_update_tm: '2025-05-20 06:30:19',
      last_update_user: 'system',
      category: 'listing',
    },
    {
      widget_use_case: 'ef54847f-8e5e-29ab-b4c6-9e40b272cb0f',
      use_case_id: 'search_term_segmented_click_statistics_v1',
      widget_ids: ['search'],
      name: 'Search-Term Segmented Click Statistics',
      tooltip: [
        {
          language: 'en',
          value: 'Statistics of clicks segmented by search term.',
        },
      ],
      order: 27,
      property_values: [
        {
          property_name: 'time_range',
          property_values: [''],
          default_values: [''],
          widget_property_values: [
            {
              widget_id: 'search',
              property_values: [''],
            },
          ],
          tooltip: [],
          string_attributes: [],
          localized_string_attributes: [],
          numeric_attributes: [],
          localized_numeric_attributes: [],
          datetime_attributes: [],
          localized_datetime_attributes: [],
        },
        {
          property_name: 'statistic_type',
          property_values: [''],
          default_values: [''],
          widget_property_values: [
            {
              widget_id: 'search',
              property_values: [''],
            },
          ],
          tooltip: [],
          string_attributes: [],
          localized_string_attributes: [],
          numeric_attributes: [],
          localized_numeric_attributes: [],
          datetime_attributes: [],
          localized_datetime_attributes: [],
        },
        {
          property_name: 'boostWeight',
          property_values: ['0.5'],
          default_values: ['0.5'],
          widget_property_values: [
            {
              widget_id: 'search',
              property_values: ['0.5'],
            },
          ],
          tooltip: [],
          string_attributes: [],
          localized_string_attributes: [],
          numeric_attributes: [],
          localized_numeric_attributes: [],
          datetime_attributes: [],
          localized_datetime_attributes: [],
        },
      ],
      string_attributes: [],
      localized_string_attributes: [],
      numeric_attributes: [],
      localized_numeric_attributes: [],
      datetime_attributes: [],
      localized_datetime_attributes: [],
      creation_tm: '2025-05-30 15:50:46',
      last_update_tm: '2025-05-30 15:50:46',
      last_update_user: 'system',
      category: 'marketing',
    },
    {
      widget_use_case: 'ecdad206-e673-f5b6-f9f8-5c825436ff7a',
      use_case_id: 'click_statistics_v1',
      widget_ids: ['similar_client', 'similar', 'related'],
      name: 'Click Statistics',
      tooltip: [
        {
          language: 'en',
          value: 'Analyze product click statistics.',
        },
      ],
      order: 22,
      property_values: [
        {
          property_name: 'time_range',
          property_values: [''],
          default_values: [''],
          widget_property_values: [
            {
              widget_id: 'similar_client',
              property_values: [''],
            },
            {
              widget_id: 'similar',
              property_values: [''],
            },
            {
              widget_id: 'related',
              property_values: [''],
            },
          ],
          tooltip: [],
          string_attributes: [],
          localized_string_attributes: [],
          numeric_attributes: [],
          localized_numeric_attributes: [],
          datetime_attributes: [],
          localized_datetime_attributes: [],
        },
        {
          property_name: 'boostWeight',
          property_values: ['0.5'],
          default_values: ['0.5'],
          widget_property_values: [
            {
              widget_id: 'similar_client',
              property_values: ['0.5'],
            },
            {
              widget_id: 'similar',
              property_values: ['0.5'],
            },
            {
              widget_id: 'related',
              property_values: ['0.5'],
            },
          ],
          tooltip: [],
          string_attributes: [],
          localized_string_attributes: [],
          numeric_attributes: [],
          localized_numeric_attributes: [],
          datetime_attributes: [],
          localized_datetime_attributes: [],
        },
        {
          property_name: 'statistic_type',
          property_values: [''],
          default_values: ['absolute'],
          widget_property_values: [
            {
              widget_id: 'similar_client',
              property_values: ['absolute'],
            },
            {
              widget_id: 'similar',
              property_values: ['rate'],
            },
            {
              widget_id: 'related',
              property_values: ['rate'],
            },
          ],
          tooltip: [],
          string_attributes: [],
          localized_string_attributes: [],
          numeric_attributes: [],
          localized_numeric_attributes: [],
          datetime_attributes: [],
          localized_datetime_attributes: [],
        },
      ],
      string_attributes: [],
      localized_string_attributes: [],
      numeric_attributes: [],
      localized_numeric_attributes: [],
      datetime_attributes: [],
      localized_datetime_attributes: [],
      creation_tm: '2025-06-10 04:44:07',
      last_update_tm: '2025-06-10 04:46:52',
      last_update_user: 'system',
      category: 'marketing',
    },
    {
      widget_use_case: 'd8083f27-047a-383c-b2a5-614300a486c0',
      use_case_id: 'personalization_affinities_reordering_v1',
      widget_ids: ['search', 'similar_client'],
      name: 'Personalization Affinities Based on Re-Ordering',
      tooltip: [
        {
          language: 'en',
          value: 'Recommend products based on re-ordering affinities.',
        },
      ],
      order: 18,
      property_values: [
        {
          property_name: 'boostWeight',
          property_values: ['0.5'],
          default_values: ['0.5'],
          widget_property_values: [
            {
              widget_id: 'search',
              property_values: ['0.9'],
            },
            {
              widget_id: 'similar_client',
              property_values: ['0.9'],
            },
          ],
          tooltip: [],
          string_attributes: [],
          localized_string_attributes: [],
          numeric_attributes: [],
          localized_numeric_attributes: [],
          datetime_attributes: [],
          localized_datetime_attributes: [],
        },
        {
          property_name: 'enabled',
          property_values: [''],
          default_values: ['false'],
          widget_property_values: [
            {
              widget_id: 'search',
              property_values: ['true'],
            },
            {
              widget_id: 'similar_client',
              property_values: ['false'],
            },
          ],
          tooltip: [],
          string_attributes: [],
          localized_string_attributes: [],
          numeric_attributes: [],
          localized_numeric_attributes: [],
          datetime_attributes: [],
          localized_datetime_attributes: [],
        },
      ],
      string_attributes: [],
      localized_string_attributes: [],
      numeric_attributes: [],
      localized_numeric_attributes: [],
      datetime_attributes: [],
      localized_datetime_attributes: [],
      creation_tm: '2025-05-29 08:29:06',
      last_update_tm: '2025-05-29 08:29:23',
      last_update_user: 'system',
      category: 'personalization',
    },
    {
      widget_use_case: '33f64e91-5fc4-5942-9c44-4e3a356ad982',
      use_case_id: 'personalization_prior_purchases_retarget_v1',
      widget_ids: ['search'],
      name: 'Personalization on Prior Purchases: Retarget',
      tooltip: [
        {
          language: 'en',
          value: 'Retarget products based on previous purchase history.',
        },
      ],
      order: 11,
      property_values: [
        {
          property_name: 'algorithm',
          property_values: [''],
          default_values: [''],
          widget_property_values: [
            {
              widget_id: 'search',
              property_values: [''],
            },
          ],
          tooltip: [],
          string_attributes: [],
          localized_string_attributes: [],
          numeric_attributes: [],
          localized_numeric_attributes: [],
          datetime_attributes: [],
          localized_datetime_attributes: [],
        },
        {
          property_name: 'boostWeight',
          property_values: ['0.5'],
          default_values: ['0.5'],
          widget_property_values: [
            {
              widget_id: 'search',
              property_values: ['0.5'],
            },
          ],
          tooltip: [],
          string_attributes: [],
          localized_string_attributes: [],
          numeric_attributes: [],
          localized_numeric_attributes: [],
          datetime_attributes: [],
          localized_datetime_attributes: [],
        },
      ],
      string_attributes: [],
      localized_string_attributes: [],
      numeric_attributes: [],
      localized_numeric_attributes: [],
      datetime_attributes: [],
      localized_datetime_attributes: [],
      creation_tm: '2025-05-29 08:50:58',
      last_update_tm: '2025-05-29 08:50:58',
      last_update_user: 'system',
      category: 'personalization',
    },
    {
      widget_use_case: 'a927ac33-b01c-32a9-7e26-bcdc35e44ddb',
      use_case_id: 'search_term_segmented_click_margin_statistics_v1',
      widget_ids: ['search', 'similar_client'],
      name: 'Search-Term Segmented Click-Margin Statistics',
      tooltip: [
        {
          language: 'en',
          value: 'Statistics of click-to-margin segmented by search term.',
        },
      ],
      order: 30,
      property_values: [
        {
          property_name: 'boostWeight',
          property_values: ['0.5'],
          default_values: ['0.5'],
          widget_property_values: [
            {
              widget_id: 'search',
              property_values: ['0.6'],
            },
            {
              widget_id: 'similar_client',
              property_values: ['0.6'],
            },
          ],
          tooltip: [],
          string_attributes: [],
          localized_string_attributes: [],
          numeric_attributes: [],
          localized_numeric_attributes: [],
          datetime_attributes: [],
          localized_datetime_attributes: [],
        },
        {
          property_name: 'time_range',
          property_values: [''],
          default_values: ['short_term'],
          widget_property_values: [
            {
              widget_id: 'search',
              property_values: ['short_term'],
            },
            {
              widget_id: 'similar_client',
              property_values: ['mid_term'],
            },
          ],
          tooltip: [],
          string_attributes: [],
          localized_string_attributes: [],
          numeric_attributes: [],
          localized_numeric_attributes: [],
          datetime_attributes: [],
          localized_datetime_attributes: [],
        },
        {
          property_name: 'statistic_type',
          property_values: [''],
          default_values: ['absolute'],
          widget_property_values: [
            {
              widget_id: 'search',
              property_values: ['rate'],
            },
            {
              widget_id: 'similar_client',
              property_values: ['absolute'],
            },
          ],
          tooltip: [],
          string_attributes: [],
          localized_string_attributes: [],
          numeric_attributes: [],
          localized_numeric_attributes: [],
          datetime_attributes: [],
          localized_datetime_attributes: [],
        },
      ],
      string_attributes: [],
      localized_string_attributes: [],
      numeric_attributes: [],
      localized_numeric_attributes: [],
      datetime_attributes: [],
      localized_datetime_attributes: [],
      creation_tm: '2025-05-29 08:50:55',
      last_update_tm: '2025-05-30 15:39:02',
      last_update_user: 'system',
      category: 'sales',
    },
  ],
  tm: '20250625035328',
  errors: [],
};
